name: Convert PPT to Image

on:
  push:
    paths:
      - "**.ppt"
      - "**.pptx"
  workflow_dispatch: # 添加这一行来启用手动触发

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Install LibreOffice
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libreoffice

      # - name: Install ImageMagick
      #   run: |
      #     sudo apt-get install -y imagemagick

      - name: Find changed PPT files
        id: changed-files
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Before commit: ${{ github.event.before }}"
          echo "After commit: ${{ github.event.after }}"

          if [ "${{ github.event_name }}" == "push" ]; then
            echo "处理 push 事件..."
            FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -E '\.ppt$|\.pptx$' || true)
          else
            echo "处理手动触发事件..."
            FILES=$(git diff --name-only HEAD^ HEAD | grep -E '\.ppt$|\.pptx$' || true)
          fi

          echo "----------------------------------------"
          echo "找到的文件列表："
          echo "$FILES"
          echo "----------------------------------------"
          echo "files=$FILES" >> $GITHUB_OUTPUT

      # - name: Convert PPT to PDF
      #   run: |
      #     # Read files from previous step
      #     IFS=$'\n' read -ra FILES <<< "${{ steps.changed-files.outputs.files }}"
      #     for file in "${FILES[@]}"; do
      #       filename=$(basename -- "$file")
      #       dirname=$(dirname -- "$file")
      #       name="${filename%.*}"

      #       # Convert to PDF
      #       libreoffice --headless --convert-to pdf "$file" --outdir "$dirname"

      #       # Convert PDF to image
      #       convert -density 300 "$dirname/$name.pdf" -quality 100 "$dirname/$name.png"
      #     done

      # - name: Commit and push changes
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"

      #     # Add all PNG files
      #     git add *.png

      #     # Commit if there are changes
      #     git diff --staged --quiet || git commit -m "Convert PPT to images"

      #     # Push changes
      #     git push
