name: Convert PPT to PDF and Image

on:
  push:
    paths:
      - '*.ppt'
      - '*.pptx'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Convert PPT/PPTX to PDF
      run: |
        sudo apt-get update
        sudo apt-get install -y libreoffice
        for file in *.ppt*; do
          libreoffice --headless --convert-to pdf "$file"
        done

    - name: Convert PDF to Image
      run: |
        sudo apt-get install -y imagemagick
        for file in *.pdf; do
          convert -density 300 "$file" -quality 100 "${file%.pdf}.png"
        done

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add *.png
        git commit -m 'Add converted images'
        git push
